installation steps completed
dependency "quart" is needed to run SimplyTranslate Web

fixes:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from quart import Quart, render_template, request
ModuleNotFoundError: No module named 'quart'